### ISSUE TITLE
can you make it in english?

### ISSUE THREAD

**Issue by MonkeyDxLuffy** [auhide/chef-gpt#2]
can you make it in english?

**Comment by auhide** [comment]
Hi @MonkeyDxLuffy,

Thank you for the interest in this project/model!
Yes, I plan on doing that in the near future. 

I'll leave this Issue open until I create the English model.

Best Regards,
auhide

**Comment by auhide** [comment]
Hi @MonkeyDxLuffy!

The English Chef GPT model has been trained and I've added it to the UI of the [Website](https://chef-gpt.streamlit.app/).
By default the used model is the English one. You can toggle between the two languages (English & Bulgarian) using the drop-down list.

Additionally, I've published it on HuggingFace's Model Hub - [auhide/chef-gpt-en](https://huggingface.co/auhide/chef-gpt-en).
From there you can download it and use it in your own projects as well!

_Please let me know if you have further suggestions!_

Best Regards,
auhide
